# Call to action, optional.
# If the link is set, the call will appear as a button.

text: |-
  The online mirror is [now available](https://codeforces.com/blog/entry/68155)!  
  Full scoreboard [here](/scoreboard.html).
link:
